# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urs', '0006_auto_20171128_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
