# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urs', '0008_auto_20171203_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp', models.CharField(default='본원', max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('booker', models.CharField(max_length=200)),
                ('date', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='img',
        ),
        migrations.AlterField(
            model_name='place',
            name='camp',
            field=models.CharField(default='본원', max_length=200),
        ),
    ]
