# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urs', '0009_auto_20171203_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='camp',
            field=models.CharField(default='', max_length=200),
        ),
    ]
